version: "3.7"

services:
  db:
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:13
    networks:
      - my-network
    ports:
      - 3300:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: db

networks:
  my-network:
